server:
  port: 9000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/uno?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
#    password: root
    password: hai123465
    type: com.alibaba.druid.pool.DruidDataSource


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false # 关闭字段名称自动驼峰转下划线
    jdbc-type-for-null: 'null'

dgs:
  graphql:
    schema-locations:
      - classpath*:schema/*.graphqls

sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: saToken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 604800 # 7天
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true


global-setting:
  # 头像上传路径
  avatar-upload-path: ./uploads/
  # 最大头像大小
  max-avatar-size: 3145728 # 3MB
  #允许的头像类型
  allowed-avatar-types: image/jpeg, image/png, image/gif

logging:
  level:
    root: info
